version: '3.8'

services:
  anydl-bot:
    build: .
    container_name: anydl-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - APP_URL=${APP_URL}
      - PORT=8000
      - AUTHORIZED_USERS=${AUTHORIZED_USERS}
      - REAL_DEBRID_API_KEY=${REAL_DEBRID_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - /tmp:/tmp
    mem_limit: 1g
    cpus: 1
